using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace YTPlayListDownloader.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Playlists",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", nullable: false),
                    Title = table.Column<string>(type: "TEXT", nullable: false),
                    Author = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Playlists", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Video",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", nullable: false),
                    Title = table.Column<string>(type: "TEXT", nullable: false),
                    Comment = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Video", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "PlaylistVideos",
                columns: table => new
                {
                    VideoId = table.Column<string>(type: "TEXT", nullable: false),
                    PlayListId = table.Column<string>(type: "TEXT", nullable: false),
                    Position = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlaylistVideos", x => new { x.VideoId, x.PlayListId });
                    table.ForeignKey(
                        name: "FK_PlaylistVideos_Playlists_PlayListId",
                        column: x => x.PlayListId,
                        principalTable: "Playlists",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PlaylistVideos_Video_VideoId",
                        column: x => x.VideoId,
                        principalTable: "Video",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Playlists",
                columns: new[] { "Id", "Author", "Title" },
                values: new object[] { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Виктор собел", "BBBGGGMMM" });

            migrationBuilder.InsertData(
                table: "Video",
                columns: new[] { "Id", "Comment", "Title" },
                values: new object[,]
                {
                    { "_8WlyB761g0", null, "[Rap Battle!] Taiga Aisaka vs Kirino Kousaka" },
                    { "-EKxzId_Sj4", null, "[米津玄師] アイネクライネ" },
                    { "-gac_HyUsfA", "群眾怒吼聲震裂壁壘，烈火般驅走黑夜，連貫歷史的正義呼喊，在今日也呼喚你", "[噪音合作社][Eugène Pottier][Pierre De Geyter] 國際歌" },
                    { "-kZBuzsZ7Ho", null, "[MyGO!!!!!] 春日影" },
                    { "0_pfGRDugxg", "Roses are red and violets are blue.\nA note of the dead is right in your view.\nA ghost on your bed you find out the rules.\nThen go for the pen and write in your room.\nThe Tokyo feds end up finding the clues.\nDon't know where you tread and in spite of your youth.\nYou're broken and dead for your crimes and induced.\n\nwith poetic justice Ryuk", "[Rap Battle!] Light Yagami vs Monika" },
                    { "0A00OqHvTOA", null, "[НЕБО НАД ГОЛОВОЙ] Искра свободы" },
                    { "0dHbpmhy1Bk", "", "[Ferdinand Radeck] Fridericus Rex Grenadiermarsch" },
                    { "0gFy1XeYKSw", null, "[strike witches] erica" },
                    { "0LwM_2h-HGc", "", "[黃連煜][桑布伊] 滅人山" },
                    { "0r399LOfHG8", null, "[Janne Da Arc] 月光花" },
                    { "1K7wktyUta0", null, "[дворы] ssshhhiiittt!" },
                    { "1TMXCpV3JfU", null, "[NEFFEX] Go!" },
                    { "2C2fAU9fn-U", null, "[keeno][初音ミクDark] 青を焚べて" },
                    { "2FgcZMqkZfc", null, "[Rap Battle!] SAYORI vs SQUIDWARD" },
                    { "2Gs9N0nlCiE", null, "[Ручной Рептилоид] Социально болен" },
                    { "2jzxrehskOw", null, "[BEYOND] 你知道我的迷惘" },
                    { "2RhWAYp-yvc", null, "[夢乃ゆき] 昨日みた夢" },
                    { "35iPH7jJLH0", null, "[一二三][初音ミク] 花が落ちたので、" },
                    { "3PXswuSz6W4", null, "[НЕБО НАД ГОЛОВОЙ] Я ХОТЕЛ БЫТЬ КОСМОНАВТОМ" },
                    { "45jSY48vd6A", null, "Säkkijärven polkka" },
                    { "4bdnip1vjhc", null, "[Corn Wave] dinosaurs" },
                    { "4ibYwtra0eY", null, "[ぽわぽわP] Astronauts FA乐器remix" },
                    { "4QXCPuwBz2E", null, "[ツユ] あの世行きのバスに乗ってさらば" },
                    { "4tW1Mhm-ZtY", null, "[金坷垃] 挥着翅膀的女(ke)孩(la)" },
                    { "4ucamH-_cPw", null, "[奧華子] あなたに好きと言われたい" },
                    { "4v7VQOILPfc", null, "[keeno] weep" },
                    { "4vbIKFMn9mU", "", "[羅大佑] 大家免著驚" },
                    { "5AuY2Jzl284", null, "[雨宮天][高橋李依][茅野愛衣][小飛鼠Amelia Khor] ちいさな冒険者" },
                    { "5c4SG9gGNWE", null, "[鄭智仁] 生命之歌" },
                    { "5DeioSB7AU4", null, "[東方萃夢想] 魔女たちの舞踏会" },
                    { "5kz1c1bvKMQ", "我們摯愛的魔法少女美樹沙耶香、佐倉杏子，於西元2011年3月3日，悄悄的離開了見瀧原市，我們痛徹心扉，就僅僅一眨眼的時間，天人永隔。她們安祥的完成了魔法少女的使命，彷彿在沉睡中做了一個美夢。夢醒了，留下陪伴我們成長過程中的點點滴滴，留下我們永恆的追思與感恩。", "[佐倉杏子@野中藍][美樹沙耶香@喜多村英梨] and I'm home" },
                    { "6gar6MONCKs", null, "[Σταμάτης Σπανουδάκης] Θά 'ρθεις σαν αστραπή" },
                    { "6mOoCFDcs3E", null, "[梶浦由記][南里侑香] 暁の車" },
                    { "6PBmiE_k12E", null, "[イヌクワチャンネル][さんひ] 聞いて。" },
                    { "6ZjgzePvoyg", null, "[黃聖依] 我不入地獄" },
                    { "7AVI8pYUSYM", null, "[keeno][初音ミクAppend] crack" },
                    { "7G0ovtPqHnI", null, "[YOASOBI] 海のまにまに" },
                    { "7NrQei36fJk", null, "[Westlife] If I Let You Go" },
                    { "87moOXPTtSk", null, "[-inai-][可不] 死のうとしたのにな" },
                    { "8J3mAIM8N60", null, "[Maksim Mrvica] croatian rhapsody" },
                    { "8pGRdRhjX3o", null, "[DECO27][初音ミク] 妄想感傷代償連盟" },
                    { "9eyyhtOrKPI", null, "[REOL] drop pop candy" },
                    { "9FaDpS_IFpM", null, "[阿隆] 神魔之塔 - 夜幕下的旅途" },
                    { "9lVPAWLWtWc", null, "[ヨルシカ] 花に亡霊" },
                    { "A_J3UhPK-Zo", null, "[梶浦由記] Credens Justitiam" },
                    { "a6j5lbt6OLQ", null, "[NEFFEX] My Way" },
                    { "ADIP3Um32Gc", null, "[ClariS] コネクト" },
                    { "AHZJh5P15i4", null, "[島谷瞳] Destiny -太陽の花-" },
                    { "aK81oAFippw", "", "[一人一首金坷垃] 烈农" },
                    { "AkBKzjlCNX0", "", "[伍佰 Wu Bai&China Blue] 楓葉" },
                    { "AY7ug521lHo", null, "[ヨルシカ] 昼鳶" },
                    { "B2HQSekxMUc", null, "[傘村トータ][Fukase][知声] ふたりぼっち同盟" },
                    { "B776HM2cZWM", null, "[初音ミク][Reol] アストロノーツ" },
                    { "BARRZDpAHfo", null, "[文藝復興樂團Renascimento] 飛蛾撲火" },
                    { "bDx8-LmNSPI", "", "[莉犬くん] いいんだよ" },
                    { "bFUnWu6hQuU", "", "[解凍三色豆] 就像吃三色豆" },
                    { "BfUQKQjSoUQ", null, "[金坷垃][别惹精神病][Marshmello] Alone" },
                    { "Bg59q4puhmg", null, "[Avril Lavigne] Girlfriend" },
                    { "bMWg0-dSP9s", null, "[傘村トータ][初音ミク] 人工呼吸" },
                    { "bnCnnY2tDOo", null, "[初音ミク] 生きるオリジナル曲 Life" },
                    { "BqbzJ4uXcNc", null, "[WI'P] せかいのおはなし" },
                    { "bzlHPlq8hIs", null, "[梶浦由記] Sis Puella Magica!" },
                    { "c_D37tFw7Z8", null, "[アフリカンサマータイム][天秤ひなみ] Forward" },
                    { "c9PEYJdwdwI", "", "[滅火器 Fire EX.] 長途夜車" },
                    { "caMRArcGhmg", null, "[FreeTempo] Dreaming" },
                    { "ceIwCBy9zcs", null, "[モンスト] 歪なる契約者" },
                    { "CHs04xmtenA", null, "[Ручной Рептилоид] Агрессивный" },
                    { "CJGSo0aZaak", null, "[傘村トータ][IA][結月ゆかり] 誰かのヒーローになりたかった" },
                    { "CkIHA_m5d84", null, "[HarryP][初音ミク] 晴天前夜" },
                    { "CkvWJNt77mU", null, "[ヨルシカ] 晴る" },
                    { "CniSkoogfZs", null, "[初音ミク] 6900000000" },
                    { "cP6VqB4klpQ", null, "[Rap Battle!] Donald Trump vs Ebenezer Scrooge" },
                    { "CPY6AML_GCY", null, "[兄弟本色 G.U.T.S] 迷途羔羊" },
                    { "CT-P8-D8CC0", null, "[伍佰 Wu Bai&China Blue] 突然的自我" },
                    { "CtRQVrhg1HY", null, "[Beyond] 真的愛你" },
                    { "d-K3bNOwhGo", null, "[JK小惡魔][白冰冰][黃乙玲] 交通部長王先生" },
                    { "D1YGeQLjdiw", null, "[Duca] アイの庭" },
                    { "D8hCn4no4O8", null, "[梶浦由記] sand dream" },
                    { "Di3R-7Y_RSI", null, "[梶浦由記] 砂塵の彼方へ" },
                    { "dl7CLaZFG1c", "stroke, roll up in the boat,you're sleeping cut your throat,I watch the blood flow,now who's got that red coat", "[Rap Battle!] George Washington vs William Wallace" },
                    { "DnLFVUi3oOU", null, "[DECO27][GUMI] モザイクロール" },
                    { "DrG1CjMWaM8", null, "[宮脇詩音] 月光" },
                    { "dSw8CucthGc", null, "[iroha][鏡音リン] 炉心融解" },
                    { "duTWwnGtGBo", null, "[解凍三色豆] 漂 流" },
                    { "Dy3qLNZyDZA", "", "[Кино] Когда твоя девушка больна" },
                    { "EGLoIaHwKfE", null, "[SadSvit] Касета" },
                    { "eiN74eBG0cU", "", "[美樹沙耶香@喜多村英梨][ансамбль песни и пляски А.В.Александрова] Служить Саяка" },
                    { "Ej0DA0BgbRU", null, "[Jeick Abrego] One Step Closer" },
                    { "ejhcSi4W568", null, "[Cypis] Gdzie jest biały węgorz" },
                    { "elql9b_31IY", null, "[Duca] ISI" },
                    { "EpAnuMO_nuk", null, "[里奈Rina] からくりx壊れたピエロ" },
                    { "epGtVG2-SAo", null, "[一二三][音街ウナ] 結い傷な" },
                    { "EQI8oKA6X4o", null, "[伍佰 Wu Bai&China Blue] 斷腸詩" },
                    { "F64yFFnZfkI", null, "[ヨルシカ] 言って。" },
                    { "fCU4VJ6DseY", null, "[初音ミク] 橙ゲノム" },
                    { "fgwBoi_6_Ys", null, "55 Giorni a Pechino" },
                    { "FLs2faYqoNU", null, "[いきものがかり] 熱情のスペクトラム" },
                    { "FQQ6Ef1iTP4", null, "[傘村トータ][初音ミク] あれほど欲した幸せを、手放す勇気を僕にくれ" },
                    { "FV_-8DWuq5w", null, "[Ploho] Вечер грустных пар" },
                    { "FWN5GCr8iqc", null, "[アフリカンサマータイム][小鳥遊めぐみ] 恒星" },
                    { "G6eARtt2mic", null, "[Kra] 絆-キズナ-" },
                    { "g9H9R2KYaVY", null, "[Διονύσιος Σολωμός] Ύμνος εις την Ελευθερίαν" },
                    { "GB3DN7B4mx4", null, "[シド] レイン" },
                    { "GBVotNefYME", null, "[Big Sean] One Man Can Change The World" },
                    { "ghoUnQMbuEw", null, "[ヨルシカ] 歩く" },
                    { "GIlMPJNk-pU", "我們摯愛的魔法少女美樹沙耶香、佐倉杏子，於西元2011年3月3日，悄悄的離開了見瀧原市，我們痛徹心扉，就僅僅一眨眼的時間，天人永隔。她們安祥的完成了魔法少女的使命，彷彿在沉睡中做了一個美夢。夢醒了，留下陪伴我們成長過程中的點點滴滴，留下我們永恆的追思與感恩。", "[佐倉杏子@野中藍][美樹沙耶香@喜多村英梨] and I'm home" },
                    { "gJ1Mz7kGVf0", null, "[Rap Battle!] Nikola Tesla vs Thomas Edison" },
                    { "gPpZJlE0Ca8", null, "[伍佰 Wu Bai&China Blue] 挪威的森林" },
                    { "GrqPwrCvPHY", null, "[傘村トータ][初音ミク] レムの魔法" },
                    { "GvFT3YqmUgw", null, "bad apple(ピアノ)" },
                    { "GVrRXhS0mLs", null, "[ヨルシカ] 風を食む" },
                    { "H0sABQm5mFY", null, "[金坷垃][坷杰倫][聖地亞戈合唱團] 陽光宅男" },
                    { "h5amxhRgsRQ", null, "[傘村トータ][可不] ちゃんとあるよ" },
                    { "HaTn3oRPtzg", null, "[Sabaton] The Last Stand" },
                    { "heviU6h0snM", null, "[宮脇詩音] 欠けた月" },
                    { "hmPqnfZMbzA", null, "[梶浦由記][Kalafina] 未来" },
                    { "HNC5eu16hEw", null, "Der Säkkijärven Polkka" },
                    { "HV-sxwH70CE", null, "[ヨルシカ] エルマ (ギター)" },
                    { "hyO3xBbf2mg", null, "[Rap Battle!] 王司徒 vs 諸葛亮" },
                    { "hZFBTnzKa54", null, "[ユリイ・カノン][GUMI] だれかの心臓になれたなら" },
                    { "iASoRE5k0Vw", "", "The British Grenadiers" },
                    { "ib8-PeMrMjo", null, "[傘村トータ][初音ミク] さよなら、僕のヒーロー" },
                    { "iCp3yL-Q6nM", null, "[楊千嬅 Miriam Yeung] 烈女" },
                    { "imSVDa7KCDU", null, "[北大力南逸峰] 我的故事" },
                    { "IV6s7IKxocU", "", "[梶浦由記] everytime you kissed me" },
                    { "jH1RNk8954Q", null, "[Ava Max] Kings & Queens" },
                    { "Jy_78LzkGsQ", null, "[モンスト] 異形なる分断者" },
                    { "jZzHK4iJ1jM", "", "The British Grenadiers (Instrumental)" },
                    { "kENX7x5-42g", null, "[Metrik] Dawnbreaker" },
                    { "KiJUDlwwznE", "", "[MC HotDog 熱狗] 阿姨 Sugar Mommy" },
                    { "kIxNIs5GzGY", null, "[Loving Caliber] Fighter" },
                    { "klbXQsHkHkA", "", "[澤井美空] Colorful" },
                    { "KLr_M5CcEJ0", null, "[傘村トータ][IA][結月ゆかり] 今日も空が綺麗だから" },
                    { "kyZz2BOy8ow", null, "[Кино] Муравейник" },
                    { "LEpMTU8pjIs", null, "[傘村トータ][GUMI] Reach for the Sky" },
                    { "LfephiFN76E", null, "[REOL] No title" },
                    { "LLV-OrsllQw", null, "[奧華子] 楔" },
                    { "lNuXbIfwXP4", null, "[伍佰 Wu Bai&China Blue] 白鴿" },
                    { "Lq2-HHP04jM", null, "[奧華子] 変わらないもの" },
                    { "LqQ_xF1LfYg", null, "[傘村トータ][Fukase] 歩き出すのだ、傘がなくとも。" },
                    { "lzAyrgSqeeE", null, "[米津玄師] orion" },
                    { "M0n_6L9_msk", null, "[Матве́й Исаа́кович Бла́нтер] Катюша" },
                    { "M2shOfNNGRk", null, "[Duca] アマオト" },
                    { "M6gcoDN9jBc", null, "[King Gnu] 逆夢" },
                    { "m7lO_hLBgq4", null, "[傘村トータ][GUMI] 18歳の責任" },
                    { "m9v6VIj500I", null, "[羅大佑] 皇后大道東" },
                    { "MaA4PBnK1k4", null, "[ALAN] Over the clouds" },
                    { "mFn8xMRo4yg", null, "[Jean-Marc Natel] À la volonté du peuple" },
                    { "mh8kOf1psQc", null, "[全明星] 夜曲" },
                    { "MOe5AOuBWv4", null, "[傘村トータ][IA][結月ゆかり] さよならだけが人生か" },
                    { "mrqKvu-rqIc", null, "[MC HotDog 熱狗] 差不多先生" },
                    { "MtwWoZ9vfJk", null, "[Santiano] Johnny Boy" },
                    { "mumUMScImLk", "", "[洛天依] 葬歌" },
                    { "mX8_pWK95JU", null, "[keeno][GUMI] fade" },
                    { "NCUVY9Gua9o", null, "[Corn Wave] evening" },
                    { "NEK43tVhWMY", null, "[MC HotDog 熱狗][張震嶽] 離開" },
                    { "NinvX4S9Es0", null, "[初音ミク] 繰り返し一粒" },
                    { "O3_MBIoz_ls", null, "[モンスト] 歪なる契約者 道中" },
                    { "o3OPrWglbBg", "", "[RADWIMPS][春茶] 愛にできることはまだあるかい" },
                    { "og42YD8cYBs", null, "[傘村トータ][IA][Fukase] Cheers" },
                    { "olHs3ykdE1c", null, "[金莎] 愛的魔法" },
                    { "p-zv4JaEz78", null, "[林亦][花粥] 长岛(林亦ED)" },
                    { "p3BHyOhVXmE", null, "Chanson de l'Oignon" },
                    { "pDylHkqNwFU", "", "[傘村トータ][結月ゆかり][初音ミク][猫村いろは][KAITO][IA][Fukase] Fragile" },
                    { "pgelkyK0XgA", null, "[初音ミク] paranoia" },
                    { "pH6tVMunSEk", "unavailable get now", "[Marin Hoxha] Lost On The Way" },
                    { "pHdJmDFYqTU", null, "[ヨルシカ] 都落ち" },
                    { "pp_-Xk-RmDc", null, "[初音ミク] パズル" },
                    { "PQDDCgrI8No", null, "[Rap Battle!] Yuno Gasai  vs Satou Matsuzaka" },
                    { "PtKBTFLUPVo", null, "[水島周平] 学科嫌い" },
                    { "ptZ4puTZbpQ", "", "[Мира Максимова][Саит Саитгалин] В этой весне" },
                    { "PvHo6zG46S4", null, "[Ludoviko Lazaro Zamenhofo] La Espero" },
                    { "q-y_AV2appc", "", "[YOASOBI] manimani" },
                    { "Q0IefxI6rXM", null, "[Ручной Рептилоид] Поколение" },
                    { "q2dbhaEEpiw", null, "[EGOIST] Planetes" },
                    { "Q76cSapPP7M", "我得到了什麼，而代價又是什麼", "[鴿稀拉][草食考拉Kaora] 選擇" },
                    { "qh6Sy67s6zM", null, "[鏡音リン] 深海シティアンダーグラウンド" },
                    { "QJq6GAZYH18", "", "[文藝復興樂團Renascimento] 飛蛾撲火" },
                    { "qJSVRia9HAI", null, "[Juha Rossi] Ievan Savitaipaleen Polkka (Mandolin)" },
                    { "QoUsw8SZ0og", null, "[傘村トータ][IA][Fukase] ドラドの悲劇" },
                    { "Qp3U_YqdWho", "", "[Johann JEG][梶浦由記][Synth V] ser una chica mágica" },
                    { "qRLPsGvya00", null, "[DECO27][GUMI] 弱虫モンブラン" },
                    { "qs61KYSvGZI", null, "[初音ミク][Synthesia] アストロノーツ (ピアノ)" },
                    { "QVVv4aICofc", null, "[ウォルピス社] COSMOSを歌ってみました" },
                    { "r105CzDvoo0", null, "[milet] Anytime Anywhere" },
                    { "rcVb6l4TpHw", null, "[Herms Niel] Erika" },
                    { "rcYhYO02f98", null, "[Sabaton] Winged Hussars" },
                    { "rEnYSN3xa3A", null, "[初音ミク] うそつき" },
                    { "RLpkmEKqfR4", null, "[A路人] 慎入！如何讓孩子愛上學習英文鬼畜rap" },
                    { "RQoysVOE_qg", null, "[Hoffmann von Fallersleben] Die gedanken sind frei" },
                    { "ry3Tupx4BL4", null, "[ヨルシカ] パレード" },
                    { "RZhm6Civp_U", null, "[モンスト][CaptainMeow] 歪なる契約者 道中 (ピアノ)" },
                    { "S4JLJVVjevI", null, "[美秀集團 Amazing Show] 捲菸 Roll-Cigg" },
                    { "S9L02o1a9h0", "", "[金坷垃] 農日" },
                    { "sa6eXtg6PgM", "", "[噪音合作社] 勞動者靈歌" },
                    { "sE2L9D5Vs7c", null, "[NEFFEX] Till I'm On Top" },
                    { "sF_dZQQPTRs", null, "[Eino Kettunen][Loituma] Ievan polkka" },
                    { "siYDPB2K0t0", null, "[Beyond] 喜歡你" },
                    { "sZR3IMkVLNk", null, "[keeno][初音ミク] scene" },
                    { "T6WI2bJrNz4", null, "[NEFFEX] No Filter" },
                    { "t7MBzMP4OzY", null, "[ヨルシカ] ヒッチコック" },
                    { "TP1iYThHWHg", null, "[アフリカンサマータイム][kohai] めぐる" },
                    { "u-h_FzQDV-Q", null, "[Secret Garden] Steps" },
                    { "u9ckcrP4S-c", null, "[劉醒] Marshmello Alone" },
                    { "UEdZyNbqYl4", null, "[ヨルシカ][猫又小粥] ウミユリ海底谭" },
                    { "Uig7N97MLCo", null, "[モンスト][CaptainMeow] 歪なる契約者 ボス (ピアノ)" },
                    { "UkDa--C624I", "", "[羅大佑] 長征" },
                    { "uoL_7cX0pCQ", null, "[傘村トータ][IA][結月ゆかり][初音ミク][Fukase][Ken] 贖罪" },
                    { "UqDByhCDBMk", null, "[Merak][TCHaruru] 天市垣~Heavenly Market Enclosure" },
                    { "uvC1tOleSJk", null, "[モンスト] 約定の人造臣機" },
                    { "uXcG3tXYNF8", null, "[Tom Paxton] Lyndon Johnson Told the Nation" },
                    { "V46K7apDziA", null, "[Mayday五月天] 諾亞方舟" },
                    { "vHn2pglEhK8", null, "[Ручной Рептилоид] Я хочу быть 2D" },
                    { "vJvoZfeGN-0", null, "[植田真梨恵] わかんないのはいやだ" },
                    { "vtJscsqrhL4", null, "[安月名莉子] かたち" },
                    { "VvShHLo88_c", null, "[MY FIRST STORY] REVIVER" },
                    { "WRgxXRUAX-Q", null, "[АнимациЯ] Ильич" },
                    { "wS8yk2dQBN4", null, "[dai] you" },
                    { "WYVPWs-qANs", null, "[Дан. Покрасс][Дм.] Песня артиллеристов" },
                    { "x-pCAngjeOw", "", "[伍佰 Wu Bai&China Blue] 淚橋" },
                    { "x5xXGqTQLUE", null, "[ANAIT] Пустота" },
                    { "X7OnmTYTzKU", "", "[理想放逐P][空崎ヒナ] 君をなぞるだけの夜" },
                    { "X9D5Qu_B6oA", "", "[許冠傑][許冠英] 半斤八兩" },
                    { "XeMVu1OYYps", null, "[梶浦由記] Decretum" },
                    { "XFqKHgd0eB0", null, "[梶浦由記][宮村優子] It's only the fairy tale" },
                    { "XQ3SxNM8rnw", null, "[dai][結月そら] そらのむこう" },
                    { "xQOXxmznGPg", null, "[佐咲紗花] Zzz" },
                    { "XXEFaMlOIhE", "", "[TANIN JAZZ] Я знаю твой телефон, но никогда не позвоню" },
                    { "Y16x_uNGjpo", null, "[moumoon] Sunshine Girl" },
                    { "Y2sPl0G1yck", null, "[ヨルシカ] エルマ" },
                    { "YA1OvUaoVuc", null, "[陳雲山][殷正洋] 東南苦行山" },
                    { "ykCuoeIqbEU", "", "[噪音合作社][Eugène Pottier][Pierre De Geyter] 國際歌" },
                    { "yrW2i4magt4", null, "[傘村トータ][ついなちゃん] だって君には彼氏がいるでしょ" },
                    { "YwfkuXAZ1Lc", "", "[ARAHIS][大島滿] БРАТЬЯ" },
                    { "yz_kza6idVA", null, "[Rap Battle!] Nico Yazawa vs 「Natsuki」 2" },
                    { "Z2MqvQMC3hQ", "", "[一人一首金坷垃] 美美背著金坷垃" },
                    { "Z8CH2UHNdHQ", "", "[Мурат Насыров] Я это ты" },
                    { "z8NxbzqPf4M", null, "[EGOIST] Ghost of a Smile" },
                    { "zesMlkz7nvM", null, "[傘村トータ][IA] 願い" },
                    { "zF1tLgSSvQs", null, "[Rizky Ayuba] You Know I'll Go Get" },
                    { "ZQqbhwH87OM", null, "[Ceui] 今、歩き出す君へ。" },
                    { "zTm666EKYRs", null, "[moumoon] Hello,shooting-star" },
                    { "ZWEHGuAdX70", null, "[モンスト] 歪なる契約者 ボス" },
                    { "ZzZ1qmXZBuY", null, "[Tymko Padura] hej sokoły" }
                });

            migrationBuilder.InsertData(
                table: "PlaylistVideos",
                columns: new[] { "PlayListId", "VideoId", "Position" },
                values: new object[,]
                {
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "_8WlyB761g0", 167 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "-EKxzId_Sj4", 208 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "-kZBuzsZ7Ho", 29 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "0_pfGRDugxg", 168 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "0A00OqHvTOA", 94 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "0dHbpmhy1Bk", 18 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "0gFy1XeYKSw", 93 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "0LwM_2h-HGc", 165 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "0r399LOfHG8", 115 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "1K7wktyUta0", 55 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "2C2fAU9fn-U", 156 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "2FgcZMqkZfc", 174 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "2Gs9N0nlCiE", 59 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "2RhWAYp-yvc", 190 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "35iPH7jJLH0", 169 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "3PXswuSz6W4", 119 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "45jSY48vd6A", 97 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "4bdnip1vjhc", 110 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "4ibYwtra0eY", 199 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "4QXCPuwBz2E", 72 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "4tW1Mhm-ZtY", 211 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "4ucamH-_cPw", 157 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "4v7VQOILPfc", 147 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "4vbIKFMn9mU", 11 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "5AuY2Jzl284", 26 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "5c4SG9gGNWE", 41 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "5DeioSB7AU4", 76 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "6gar6MONCKs", 101 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "6mOoCFDcs3E", 88 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "6PBmiE_k12E", 204 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "6ZjgzePvoyg", 144 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "7AVI8pYUSYM", 141 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "7G0ovtPqHnI", 128 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "7NrQei36fJk", 77 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "87moOXPTtSk", 145 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "8J3mAIM8N60", 74 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "8pGRdRhjX3o", 148 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "9eyyhtOrKPI", 216 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "9FaDpS_IFpM", 207 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "9lVPAWLWtWc", 203 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "A_J3UhPK-Zo", 51 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "a6j5lbt6OLQ", 21 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ADIP3Um32Gc", 80 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "AHZJh5P15i4", 66 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "aK81oAFippw", 191 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "AkBKzjlCNX0", 13 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "AY7ug521lHo", 175 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "B2HQSekxMUc", 158 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "B776HM2cZWM", 212 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "bDx8-LmNSPI", 48 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "bFUnWu6hQuU", 177 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "bMWg0-dSP9s", 181 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "bnCnnY2tDOo", 184 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "BqbzJ4uXcNc", 109 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "bzlHPlq8hIs", 89 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "c_D37tFw7Z8", 30 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "c9PEYJdwdwI", 129 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "caMRArcGhmg", 154 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ceIwCBy9zcs", 28 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "CHs04xmtenA", 60 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "CJGSo0aZaak", 180 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "CkIHA_m5d84", 133 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "CkvWJNt77mU", 49 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "CniSkoogfZs", 131 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "cP6VqB4klpQ", 82 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "CT-P8-D8CC0", 64 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "d-K3bNOwhGo", 44 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "D1YGeQLjdiw", 40 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "D8hCn4no4O8", 86 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Di3R-7Y_RSI", 57 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "dl7CLaZFG1c", 79 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "DnLFVUi3oOU", 35 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "DrG1CjMWaM8", 164 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "dSw8CucthGc", 112 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "duTWwnGtGBo", 176 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Dy3qLNZyDZA", 4 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "EGLoIaHwKfE", 92 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "eiN74eBG0cU", 23 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Ej0DA0BgbRU", 118 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ejhcSi4W568", 105 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "elql9b_31IY", 142 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "EpAnuMO_nuk", 68 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "epGtVG2-SAo", 161 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "EQI8oKA6X4o", 171 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "F64yFFnZfkI", 205 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "fCU4VJ6DseY", 170 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "fgwBoi_6_Ys", 106 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "FLs2faYqoNU", 126 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "FQQ6Ef1iTP4", 151 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "FV_-8DWuq5w", 90 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "FWN5GCr8iqc", 31 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "g9H9R2KYaVY", 27 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "GB3DN7B4mx4", 120 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "GBVotNefYME", 209 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ghoUnQMbuEw", 166 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "GIlMPJNk-pU", 43 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "gJ1Mz7kGVf0", 73 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "gPpZJlE0Ca8", 67 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "GrqPwrCvPHY", 150 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "GvFT3YqmUgw", 192 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "GVrRXhS0mLs", 114 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "h5amxhRgsRQ", 178 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "HaTn3oRPtzg", 37 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "heviU6h0snM", 162 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "hmPqnfZMbzA", 39 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "HNC5eu16hEw", 96 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "hyO3xBbf2mg", 213 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "hZFBTnzKa54", 189 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "iASoRE5k0Vw", 6 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ib8-PeMrMjo", 179 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "iCp3yL-Q6nM", 183 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "imSVDa7KCDU", 210 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "IV6s7IKxocU", 15 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "jH1RNk8954Q", 69 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Jy_78LzkGsQ", 65 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "jZzHK4iJ1jM", 8 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "kENX7x5-42g", 56 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "KiJUDlwwznE", 20 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "kIxNIs5GzGY", 107 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "klbXQsHkHkA", 108 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "KLr_M5CcEJ0", 127 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "kyZz2BOy8ow", 121 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "LEpMTU8pjIs", 136 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "LfephiFN76E", 218 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "LLV-OrsllQw", 217 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "lNuXbIfwXP4", 200 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Lq2-HHP04jM", 159 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "LqQ_xF1LfYg", 153 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "lzAyrgSqeeE", 206 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "M0n_6L9_msk", 50 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "M2shOfNNGRk", 42 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "m7lO_hLBgq4", 125 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "m9v6VIj500I", 104 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "mFn8xMRo4yg", 117 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "MOe5AOuBWv4", 146 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "mrqKvu-rqIc", 214 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "MtwWoZ9vfJk", 137 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "mumUMScImLk", 116 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "mX8_pWK95JU", 54 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "NCUVY9Gua9o", 45 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "NEK43tVhWMY", 201 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "NinvX4S9Es0", 185 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "o3OPrWglbBg", 17 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "olHs3ykdE1c", 182 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "p-zv4JaEz78", 134 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "p3BHyOhVXmE", 61 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "pDylHkqNwFU", 10 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "pgelkyK0XgA", 111 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "pHdJmDFYqTU", 130 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "pp_-Xk-RmDc", 186 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "PQDDCgrI8No", 172 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "PtKBTFLUPVo", 78 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ptZ4puTZbpQ", 14 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "PvHo6zG46S4", 46 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "q-y_AV2appc", 2 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Q0IefxI6rXM", 58 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "q2dbhaEEpiw", 140 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Q76cSapPP7M", 7 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "qh6Sy67s6zM", 83 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "QJq6GAZYH18", 19 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "qJSVRia9HAI", 70 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Qp3U_YqdWho", 25 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "qRLPsGvya00", 219 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "qs61KYSvGZI", 193 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "QVVv4aICofc", 135 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "r105CzDvoo0", 99 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "rcVb6l4TpHw", 98 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "rcYhYO02f98", 38 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "rEnYSN3xa3A", 132 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "RLpkmEKqfR4", 215 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "RQoysVOE_qg", 52 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ry3Tupx4BL4", 84 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "S4JLJVVjevI", 53 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "S9L02o1a9h0", 197 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "sa6eXtg6PgM", 3 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "sF_dZQQPTRs", 71 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "siYDPB2K0t0", 187 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "sZR3IMkVLNk", 124 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "t7MBzMP4OzY", 198 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "TP1iYThHWHg", 32 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "u-h_FzQDV-Q", 36 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "u9ckcrP4S-c", 196 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "UEdZyNbqYl4", 194 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "UkDa--C624I", 1 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "uoL_7cX0pCQ", 160 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "UqDByhCDBMk", 152 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "uvC1tOleSJk", 75 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "uXcG3tXYNF8", 123 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "V46K7apDziA", 113 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "vHn2pglEhK8", 100 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "vJvoZfeGN-0", 202 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "vtJscsqrhL4", 87 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "WRgxXRUAX-Q", 155 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "wS8yk2dQBN4", 34 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "WYVPWs-qANs", 102 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "x-pCAngjeOw", 12 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "x5xXGqTQLUE", 91 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "X7OnmTYTzKU", 16 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "X9D5Qu_B6oA", 139 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "XeMVu1OYYps", 62 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "XFqKHgd0eB0", 47 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "XQ3SxNM8rnw", 33 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "xQOXxmznGPg", 81 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "XXEFaMlOIhE", 22 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Y16x_uNGjpo", 122 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Y2sPl0G1yck", 85 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "YA1OvUaoVuc", 95 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ykCuoeIqbEU", 5 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "yrW2i4magt4", 138 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "YwfkuXAZ1Lc", 9 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "yz_kza6idVA", 173 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Z2MqvQMC3hQ", 188 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "Z8CH2UHNdHQ", 24 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "z8NxbzqPf4M", 143 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "zesMlkz7nvM", 149 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "zF1tLgSSvQs", 195 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ZQqbhwH87OM", 63 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "zTm666EKYRs", 163 },
                    { "PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip", "ZzZ1qmXZBuY", 103 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_PlaylistVideos_PlayListId",
                table: "PlaylistVideos",
                column: "PlayListId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PlaylistVideos");

            migrationBuilder.DropTable(
                name: "Playlists");

            migrationBuilder.DropTable(
                name: "Video");
        }
    }
}
