# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: contributor statistics

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Microsoft JhengHei font
      run: |
        if [ ! -d "$HOME/.fonts" ] ; then
            mkdir $HOME/.fonts
            echo -e "Directory ~/.fonts/ created.\n"
        fi
        wget -O SourceHanSansHWSC.zip https://github.com/adobe-fonts/source-han-sans/releases/download/2.004R/SourceHanSansHWSC.zip
        echo "Download completed"
        
        unzip SourceHanSansHWSC.zip
        echo "unzip completed"

        # copy fonts to font directory
        cp -i OTF/SimplifiedChineseHW/SourceHanSansHWSC-Regular.otf $HOME/share/fonts/SourceHanSans
        cp -i OTF/SimplifiedChineseHW/SourceHanSansHWSC-Bold.otf $HOME/share/fonts/SourceHanSans
        echo "copy completed"
        
        sudo fc-cache -fv

        if [ -e "SourceHanSansHWSC.zip" ] ; then
            rm SourceHanSansHWSC.zip  
        fi
        if [ -d "Open_Data" ] ; then
            rm -r Open_Data
        fi
      shell: bash
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Update statistics
      run: dotnet /home/runner/work/YTPlayListDownloader/YTPlayListDownloader/bin/Release/net6.0/YTPlayListDownloader.dll stat
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "nppstcc1001050311@gmail.com"
        git config --local user.name "sobel"
        git add --all
        if [ -n "$(git status --porcelain)" ]; then
           git commit -m "update contributor statistics" -a
           echo "::set-output name=push::true"
        else
           echo "::set-output name=push::false"
        fi
      shell: bash
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
