# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: contributor statistics

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cjk font
      run: sudo apt-get install fonts-noto-cjk
      shell: bash
